title: Riley Peterlinz
author: Riley Peterlinz
email: rpeterlinz@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  About Me
# baseurl: "/jekyll-theme-kagami"
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: manni # this specifies color scheme for syntax highlighting
github_username: cardiacmangoes
# google_analytics:

# Build settings
markdown: kramdown
mathjax: true
# theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock